name: Name Insights
values:
  - key: name
    value: michael
    enabled: true
    type: default
  - key: name1
    value: michael
    enabled: true
    type: default
  - key: name2
    value: jane
    enabled: true
    type: default
  - key: country_id
    value: US
    enabled: true
    type: default
